### ISSUE TITLE
Build failure with "skipLibCheck=false"

### ISSUE THREAD

**Issue by ckddbs** [iTwin/viewer-sample-angular#16]
```
Error: node_modules/@itwin/core-bentley/lib/cjs/Tracing.d.ts:1:15 - error TS2614: Module '"@opentelemetry/api"' has no exported member 'SpanAttributes'. Did you mean to use 'import SpanAttributes from "@opentelemetry/api"' instead?

1 import type { SpanAttributes, SpanContext, SpanOptions, Tracer } from "@opentelemetry/api";

```
<img width="1443" alt="Screenshot 2022-12-16 at 3 36 40 PM" src="https://user-images.githubusercontent.com/22387591/208038433-f814b857-5bf7-45c2-9c58-3adffedf580b.png">

**Comment by aruniverse** [comment]
Check your lockfile, what version of `@opentelemetry/api` is getting pulled into your node_modules?
I see it's available in `1.0.4` which is the version we use and have pinned in core-bentley.
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/11051042/208116730-23fbb7f5-7a7f-461f-b1c1-5c52b273ba10.png">

**Comment by ckddbs** [comment]
Same version with https://github.com/iTwin/viewer-sample-angular/blob/main/package-lock.json.
And @itwin/core-bentley has @opentelemetry/api as devDependencies.

**Comment by aruniverse** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/11051042/208120882-f6e0c26b-7e2a-4608-98a3-60991e83764b.png">

So there are multiple copies of opentelemetry/api, mostly due to other dependencies pulling in a different version. 

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/11051042/208122733-4fc89bbb-e79e-418f-aa0c-58ed31914a43.png">
If you look closely, on our side we're just importing a type, which when compiled to javascript will not exist.

I recommend always turning on the `skipLibCheck` flag, mostly due to being unable to control transitive deps being pulled into your app.

**Comment by ckddbs** [comment]
Our app has many dependencies besides iTwin, so we don't want to turn on the `skipLibCheck` flag. If core-bently uses the library, why don't you add it as dependencies or peer-dependencies?

**Comment by aruniverse** [comment]
We're only using the package for types, theres no reason for it to be direct or peer dependency.

https://www.typescriptlang.org/tsconfig#skipLibCheck

"Rather than doing a full check of all d.ts files, TypeScript will type check the code you specifically refer to in your app’s source code."

Why would you want to type check everything in your node modules?
